// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Todo struct {
	ID        int32
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
	Completed bool
	UserID    uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
